### PR TITLE
Add chromem-go to vector databases

### PR DESCRIPTION
**Pull request by philippgille**
Hi :wave: , saw your site on HN recently, and I happen to work on a vector database in Go.

Most vector databases are either closed source (Pinecone), not embeddable (Qdrant, Milvus, Weaviate) or only embeddable in Python (Chroma). [chromem-go](https://github.com/philippgille/chromem-go) targets this missing piece: Write a Go app and embed the vector database, without needing to set up a separate server.

I'd be happy if the project could be featured on your ecosystem overview!

### CODE REVIEW

**Comment by philippgille** [comment]
PS: I wasn't sure what to use as `weight`, feel free to change it or ask me to change it

**Comment by aprxi** [comment]
Sorry have to reject this for the specific category. While it fits, its simply already crowded.

However. Think its more useful to add a new category "ai-libraries-for-go". As more links get added, will likely create separate tabs for language specific implementations.

So if you could create the category, add it to column 1, 2 or 3 (does not really matter for now), will merge it.

**Comment by philippgille** [comment]
OK, I pushed the change.

I personally find it harder to find things when there are so many categories, and I'm not sure about some of the distinctions (e.g. "WebUIs for LLMs" vs "LocalUIs for LLMs", both work with local models / local inference, just one is a web app and one a native app, but for most people looking for a LLM UI probably both fit the bill), and similar projects like the [CNCF landscape](https://landscape.cncf.io/) also seem to lean towards more general categories entries, but let's see how the categories develop and then some can still be consolidated later :+1:

**Comment by aprxi** [comment]
Concur its not yet ideal, and yes there is indeed some small overlap in categories at this moment.

This will most certainly be reorganised later, thinking tagging things in one way or another may work. So in your case, you could have both "GoLang" and "VectorDB", which would help a Go developer find your site.

The CNCF landcape looks horrific to me personally, as this cant possibly help people find what they (may) need.

Either way. Think its useful to have language specific implementations grouped together as a first step for now.

**Comment by philippgille** [comment]
> This will most certainly be reorganised later, thinking tagging things in one way or another may work. So in your case, you could have both "GoLang" and "VectorDB", which would help a Go developer find your site.

The tagging sounds like a good idea :+1: 

Thanks for merging :bowing_man:

**Pull request merged**
